import type { Shop, DiscountTile } from "./types";

export const featuredShops: Shop[] = [
  {
    id: "fs1",
    name: "PowerFit",
    category: "Sport Fashion",
    avatar: "/placeholders/avatar.svg",
    banner: "/placeholders/lifestyle.svg",
    verified: true,
    rating: 4.5,
    reviews: 324,
    itemsSoldCount: "2300+ sels",
    yearsSelling: "3 year seller",
    tag: { label: "Fast shipping", variant: "shipping" },
  },
  {
    id: "fs2",
    name: "Nike",
    category: "Sport Fashion",
    avatar: "/placeholders/avatar.svg",
    banner: "/placeholders/lifestyle.svg",
    verified: true,
    rating: 5.0,
    reviews: 3000,
    itemsSoldCount: "8400+ sels",
    yearsSelling: "10 year seller",
    tag: { label: "Top Seller", variant: "topSeller" },
    isFollowing: true,
  },
  {
    id: "fs3",
    name: "kymez mini",
    category: "Casual Wear",
    avatar: "/placeholders/avatar.svg",
    banner: "/placeholders/lifestyle.svg",
    rating: 4.7,
    reviews: 612,
    itemsSoldCount: "1500+ sels",
    yearsSelling: "2 year seller",
    isFollowing: true,
  },
  {
    id: "fs4",
    name: "Adam Land",
    category: "Men's Style",
    avatar: "/placeholders/avatar.svg",
    banner: "/placeholders/lifestyle.svg",
    verified: true,
    rating: 4.9,
    reviews: 2104,
    itemsSoldCount: "5200+ sels",
    yearsSelling: "6 year seller",
    tag: { label: "Top Seller", variant: "topSeller" },
  },
  {
    id: "fs5",
    name: "innovate",
    category: "Lifestyle",
    avatar: "/placeholders/avatar.svg",
    banner: "/placeholders/lifestyle.svg",
    rating: 4.7,
    reviews: 198,
    itemsSoldCount: "900+ sels",
    yearsSelling: "1 year seller",
    tag: { label: "Fast shipping", variant: "shipping" },
  },
];

const BG_IMAGES = [
  "/mocks/images/discount-banners/background/Group%20427318349.png",
  "/mocks/images/discount-banners/background/Group%20427318350.png",
  "/mocks/images/discount-banners/background/Group%20427318350-1.png",
  "/mocks/images/discount-banners/background/Group%20427318352.png",
  "/mocks/images/discount-banners/background/Group%20427318352-1.png",
];

const MAIN_IMAGES = [
  "/mocks/images/discount-banners/main-images/image%20778.png",
  "/mocks/images/discount-banners/main-images/image%20778-1.png",
  "/mocks/images/discount-banners/main-images/image%20778-2.png",
  "/mocks/images/discount-banners/main-images/image%20778-3.png",
  "/mocks/images/discount-banners/main-images/Frame%20427318391.png",
  "/mocks/images/discount-banners/main-images/Frame%20427318398.png",
];

export const discountTiles: DiscountTile[] = [
  {
    id: "d1",
    percent: 20,
    image: MAIN_IMAGES[0],
    bgImage: BG_IMAGES[0],
    shopName: "Adam Land",
    shopCategory: "Women's Fashion",
    verified: true,
    background: "linear-gradient(135deg, #ff6b35 0%, #f7411a 50%, #c41e0b 100%)",
  },
  {
    id: "d2",
    percent: 30,
    image: MAIN_IMAGES[1],
    bgImage: BG_IMAGES[1],
    shopName: "Adam Land",
    shopCategory: "Women's Fashion",
    verified: true,
    background: "linear-gradient(135deg, #1e3a8a 0%, #1e6cd9 50%, #2563eb 100%)",
  },
  {
    id: "d3",
    percent: 20,
    image: MAIN_IMAGES[2],
    bgImage: BG_IMAGES[2],
    shopName: "Adam Land",
    shopCategory: "Women's Fashion",
    verified: true,
    background: "linear-gradient(135deg, #065f46 0%, #047857 50%, #059669 100%)",
  },
  {
    id: "d4",
    percent: 20,
    image: MAIN_IMAGES[3],
    bgImage: BG_IMAGES[3],
    shopName: "Adam Land",
    shopCategory: "Women's Fashion",
    verified: true,
    background: "linear-gradient(135deg, #1d4ed8 0%, #2563eb 50%, #3b82f6 100%)",
  },
  {
    id: "d5",
    percent: 50,
    image: MAIN_IMAGES[4],
    bgImage: BG_IMAGES[4],
    shopName: "Adam Land",
    shopCategory: "Women's Fashion",
    verified: true,
    background: "linear-gradient(135deg, #991b1b 0%, #dc2626 50%, #ef4444 100%)",
  },
  {
    id: "d6",
    percent: 20,
    image: MAIN_IMAGES[5],
    bgImage: BG_IMAGES[0],
    shopName: "Adam Land",
    shopCategory: "Women's Fashion",
    verified: true,
    background: "linear-gradient(135deg, #ff6b35 0%, #f7411a 50%, #c41e0b 100%)",
  },
];
