import type { Shop, DiscountTile } from "./types";

export const featuredShops: Shop[] = [
  {
    id: "fs1",
    name: "PowerFit",
    category: "Sport Fashion",
    avatar: "/placeholders/avatar.svg",
    banner: "/placeholders/lifestyle.svg",
    verified: true,
    rating: 4.5,
    reviews: 324,
    itemsSoldCount: "2300+ sels",
    yearsSelling: "3 year seller",
    tag: { label: "Fast shipping", variant: "shipping" },
  },
  {
    id: "fs2",
    name: "Nike",
    category: "Sport Fashion",
    avatar: "/placeholders/avatar.svg",
    banner: "/placeholders/lifestyle.svg",
    verified: true,
    rating: 5.0,
    reviews: 3000,
    itemsSoldCount: "8400+ sels",
    yearsSelling: "10 year seller",
    tag: { label: "Top Seller", variant: "topSeller" },
    isFollowing: true,
  },
  {
    id: "fs3",
    name: "kymez mini",
    category: "Casual Wear",
    avatar: "/placeholders/avatar.svg",
    banner: "/placeholders/lifestyle.svg",
    rating: 4.7,
    reviews: 612,
    itemsSoldCount: "1500+ sels",
    yearsSelling: "2 year seller",
    isFollowing: true,
  },
  {
    id: "fs4",
    name: "Adam Land",
    category: "Men's Style",
    avatar: "/placeholders/avatar.svg",
    banner: "/placeholders/lifestyle.svg",
    verified: true,
    rating: 4.9,
    reviews: 2104,
    itemsSoldCount: "5200+ sels",
    yearsSelling: "6 year seller",
    tag: { label: "Top Seller", variant: "topSeller" },
  },
  {
    id: "fs5",
    name: "innovate",
    category: "Lifestyle",
    avatar: "/placeholders/avatar.svg",
    banner: "/placeholders/lifestyle.svg",
    rating: 4.7,
    reviews: 198,
    itemsSoldCount: "900+ sels",
    yearsSelling: "1 year seller",
    tag: { label: "Fast shipping", variant: "shipping" },
  },
];

export const discountTiles: DiscountTile[] = [
  {
    id: "d1",
    percent: 20,
    image: "/placeholders/lifestyle.svg",
    shopName: "Pearl1234",
    background: "linear-gradient(135deg, #c4b5fd, #a78bfa)",
  },
  {
    id: "d2",
    percent: 30,
    image: "/placeholders/lifestyle.svg",
    shopName: "Nike 11",
    background: "linear-gradient(135deg, #fed7aa, #fdba74)",
  },
  {
    id: "d3",
    percent: 20,
    image: "/placeholders/lifestyle.svg",
    shopName: "Adam Land",
    background: "linear-gradient(135deg, #fcd34d, #f59e0b)",
  },
  {
    id: "d4",
    percent: 20,
    image: "/placeholders/lifestyle.svg",
    shopName: "Pearl1234",
    background: "linear-gradient(135deg, #fda4af, #f43f5e)",
  },
  {
    id: "d5",
    percent: 50,
    image: "/placeholders/lifestyle.svg",
    shopName: "Pearl1234",
    background: "linear-gradient(135deg, #fb7185, #e11d48)",
  },
  {
    id: "d6",
    percent: 20,
    image: "/placeholders/lifestyle.svg",
    shopName: "Adam Land",
    background: "linear-gradient(135deg, #fb923c, #ea580c)",
  },
];
