import type { ComponentType } from "react";
import type { IconProps } from "@solar-icons/react";

export type LucideIcon = ComponentType<IconProps>;
export type LucideProps = IconProps;

export {
  AddCircle as Plus,
  AddCircle as PlusIcon,
  AddCircle as PlusCircle,
  AddCircle as PlusCircleIcon,
  AltArrowDown as ChevronDown,
  AltArrowDown as ChevronDownIcon,
  AltArrowLeft as ChevronLeft,
  AltArrowLeft as ChevronLeftIcon,
  AltArrowRight as ChevronRight,
  AltArrowRight as ChevronRightIcon,
  AltArrowUp as ChevronUp,
  AltArrowUp as ChevronUpIcon,
  ArrowDown,
  ArrowDown as ArrowDownIcon,
  ArrowLeft,
  ArrowLeft as ArrowLeftIcon,
  ArrowRight,
  ArrowRight as ArrowRightIcon,
  ArrowUp,
  ArrowUp as ArrowUpIcon,
  Box as Package,
  Box as PackageIcon,
  Calendar,
  Calendar as CalendarIcon,
  CalendarMinimalistic as CalendarDays,
  CalendarMinimalistic as CalendarDaysIcon,
  Camera,
  Camera as CameraIcon,
  Card as CreditCard,
  Card as CreditCardIcon,
  ChatRound as MessageCircle,
  ChatRound as MessageCircleIcon,
  ChatRoundDots as MessageCircleMore,
  ChatRoundLine as MessageSquare,
  CheckCircle as Check,
  CheckCircle as CheckIcon,
  CheckCircle as CheckCircle2,
  CheckCircle as CheckCircle2Icon,
  CheckCircle as CheckCircleIcon,
  CloseCircle as X,
  CloseCircle as XIcon,
  CloseCircle as XCircle,
  CloseCircle as XCircleIcon,
  Copy,
  Copy as CopyIcon,
  Cursor as MousePointer,
  DangerCircle as AlertCircle,
  DangerCircle as AlertCircleIcon,
  DangerTriangle as AlertTriangle,
  DangerTriangle as AlertTriangleIcon,
  Delivery as Truck,
  Delivery as TruckIcon,
  Eye,
  Eye as EyeIcon,
  EyeClosed as EyeOff,
  EyeClosed as EyeOffIcon,
  Filter as Filter2,
  Filters as Filter,
  Filters as FilterIcon,
  HamburgerMenu as Menu,
  HamburgerMenu as MenuIcon,
  Heart,
  Heart as HeartIcon,
  Home,
  Home as HomeIcon,
  InfoCircle as Info,
  InfoCircle as InfoIcon,
  Like as ThumbsUp,
  Like as ThumbsUpIcon,
  Link,
  Link as LinkIcon,
  Magnifer as Search,
  Magnifer as SearchIcon,
  MapPoint as MapPin,
  MapPoint as MapPinIcon,
  MedalRibbon as Award,
  MenuDots as MoreHorizontal,
  MenuDots as MoreHorizontalIcon,
  MenuDots as Ellipsis,
  MenuDots as EllipsisIcon,
  MinusCircle as Minus,
  MinusCircle as MinusIcon,
  Pause,
  Pause as PauseIcon,
  Pen as Pencil,
  Pen as PencilIcon,
  Pen as Edit,
  Pen as EditIcon,
  Play,
  Play as PlayIcon,
  QuestionCircle as HelpCircle,
  QuestionCircle as HelpCircleIcon,
  Refresh as Loader,
  Refresh as Loader2,
  Refresh as LoaderIcon,
  Refresh as Loader2Icon,
  Refresh as LoaderCircle,
  Refresh as RefreshCw,
  Refresh as RotateCw,
  Reply,
  Ruler,
  Ruler as RulerIcon,
  ShareCircle as Share,
  ShareCircle as Share2,
  Shop as Store,
  Shop as StoreIcon,
  Sidebar as PanelLeft,
  Sidebar as PanelLeftIcon,
  Sidebar as PanelRight,
  Sidebar as PanelRightIcon,
  SortVertical as ChevronsUpDown,
  SortVertical as ChevronsUpDownIcon,
  Star,
  Star as StarIcon,
  Ticket,
  Ticket as TicketIcon,
  TrashBinMinimalistic as Trash,
  TrashBinMinimalistic as TrashIcon,
  TrashBinMinimalistic as Trash2,
  TrashBinMinimalistic as Trash2Icon,
  Tuning2 as SlidersHorizontal,
  Tuning2 as SlidersHorizontalIcon,
  Tuning2 as Settings2,
  UndoLeft as Undo2,
  UndoLeft,
  UndoLeftRound as CornerUpLeft,
  User as UserRound,
  User as UserRoundIcon,
  User as UserIcon,
  User,
  UserCircle as CircleUserRound,
  UserCircle as CircleUser,
  VerifiedCheck as BadgeCheck,
  VerifiedCheck as BadgeCheckIcon,
  VolumeLoud as Volume2,
  VolumeLoud as Volume2Icon,
  Volume,
  Volume as VolumeIcon,
} from "@solar-icons/react";

export { CheckCircle as Circle } from "@solar-icons/react";
